#Belajar OUTPUT
print("hello World")
print("Nama Saya Maulana")
print("Saya Lahir Di Jakarta")
print("Saya Berumur 15 Tahun")
print("Saya Tinggal Di Kota Depok")
print("Alamat Rumah Saya")
print("Berada Di Jl.Kramat Benda 2 ")
print("RT 05/28")
print("Kel.Baktijaya Kec.Sukmajaya")
print("Saya Mempunyai Hoby Bermain Futsal")